# Site settings
title: Crushed by Code
email: gnclmorais@gmail.com
description: A (rather technical) blog about (mostly) web development.

# https://ching-wang.io/posts/twitter-card-and-opengraph-with-jekyll
lang: en_GB
twitter:
  username: gnclmorais
  card: summary

# Social
twitter_username:   gnclmorais
github_username:    gnclmorais
dribbble_username:  gnclmorais
instagram_username: gnclmorais
spotify_username:   gnclmorais

# Build settings
markdown: kramdown
permalink: /:title
exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'Makefile'
  - 'README.md'
  - '_config.yml'
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Sass
sass:
  style: compressed
