# Site settings
title: Crushed by Code
email: gnclmorais@gmail.com
description: A (rather technical) blog about (mostly) web development.
baseurl: /

# Social
twitter_username:   gnclmorais
github_username:    gnclmorais
dribbble_username:  gnclmorais
instagram_username: gnclmorais
spotify_username:   gnclmorais

# Content

# Build settings
markdown: kramdown
permalink: /:title
exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'Makefile'
  - 'README.md'
  - '_config.yml'

# Sass
sass:
  style: compressed
